# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ChickenOrTheEggApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase iOS SDK pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

end
